export enum HttpStatus {
  NO_HTTP_CODE = 0,
  OK = 200,
  BAD_REQUEST_ERROR = 400,
  UNAUTHORIZED_ERROR = 401,
  RESOURCE_NOT_FOUND_ERROR = 404,
  METHOD_NOT_ALLOWED_ERROR = 405,
  INTERNAL_SERVER_ERROR = 500
}
